config/routes.rb
Rails.application.routes.draw do

   get 'welcome/index'
   get 'articles/view_all'
   get 'articles/new'

  resources :articles do
    resources :comments
  end
  resources :reviews

  root 'articles#new'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments , dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 http_basic_authenticate_with name: "nitesh", password: "secret", except: [:index, :show]
	
  def new
		@article = Article.new
	end
	
	def edit
    @article = Article.find(params[:id])
	end
    
  def index
    @articles = Article.all
  end

  def view_all
    @articles=Article.all
    render :action => :index
    return
  end	
	
	def show
    @article = Article.find(params[:id])
  end
 
	def create
		# render plain: params[:article].inspect
		@article = Article.new(article_params)
		 # debugger
    if @article.save
       redirect_to article_path(@article.id)
    else
       render 'new'
    end
  end

  def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to article_path(@article.id)
  else
    render 'edit'
  end
end

  def destroy
      @article=Article.find(params[:id])
      @article.destroy
      redirect_to :action => 'index'
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
	
end
# Article.new({:title => 'val','text' => 'val',})

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

http_basic_authenticate_with name: "nitesh", password: "secret", only: :destroy

def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
 <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ol>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ol>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  <%= render :partial => 'form', locals: {:f => f} %>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article.id) %></td>
      <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
      <td><%= link_to 'destroy',article_path(article.id), method: 'delete', 
                      data: { confirm: 'Are you sure want to delete?' }%>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back to home page' , new_article_path %>

app/views/articles/new.html.erb
<h1> New Article </h1>
<%= form_for @article, url: articles_path do |f| %>
  <%= render :partial => 'form', locals: {:f => f} %>
  <p> 
    <%=link_to 'View all',articles_view_all_path %>
   
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render :partial => '/comments/comment' %>

<h2>Add a comment:</h2>
<%= render :partial => '/comments/form' %>
 

<p> 
  <%= link_to 'Back', articles_path %>
  <%= link_to 'Edit', edit_article_path(@article) %>
</p>

app/views/comments/_comment.html.erb
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
  <%= link_to 'Destroy Comment', [comment.article, comment],method: :delete,
               data: { confirm: 'Are you sure want to delete comment?' } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/welcome/index.html.erb
<h1> hello rails
</h1>